---
title: "Project_selection"
author: "Catrine Høm, Julie Zimmermann, Oriade Simpson and Paolo Federico"
date: '2022-06-10'
output:
  ioslides_presentation:
    widescreen: true
    incremental: false
    logo: DTU_logo.png
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Which question do we want to answer?

Goal:  Defining the optimal gene signatures for sub-typing

Do the gene expression signatures predict the subtypes of Lung Adenocarcenoma?


## Which data are we using ?

The cohort that has been selected for analysis is the **TCGA Lung Adenocarcinoma (LUAD)** gene expression RNASeq data and Phenotype data.

These datasets were sourced from the University of California Santa Cruz DATASETS on the xenabrowser.net webpage.  

The RNASeq gene expression data contain 576 samples and 20,531 genes. 

The phenotype data contain 706 samples and 148 identifiers. 

The expression subtypes in the phenotype data are:

* Magnoid

* Squamoid 

* & Bronchioid

## How are we going to do that?

Use machine learning methods such as K-Nearest Neighbours to find some clusters 
Compare different classification methods such as support vector machine and ..
